#!/bin/sh
# Получаем абсолютный путь до каталога скрипта
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

# Переходим в эту директорию
cd "$SCRIPT_DIR" || exit 1
cd web

python ../lib/generate.py && python -m http.server --cgi